### ISSUE TITLE
page.must_have_content not working

### ISSUE THREAD

**Issue by alec-c4** [ordinaryzelig/capybara_minitest_spec#10]
Hi,
on attempt to run following test
```
Then(/^I should see "(.*?)"$/) do |string|
  page.must_have_content(string)
end
```

i see error

```
    Then I should see "Test" # features/step_definitions/pages_steps.rb:9
      undefined method `assert_page_has_content' for nil:NilClass (NoMethodError)
      (eval):4:in `must_have_content'
      ./features/step_definitions/pages_steps.rb:10:in `/^I should see "(.*?)"$/'
      features/can_access_home.feature:7:in `Then I should see "Test"'
```

how to fix it?

**Comment by toby-1-kenobi** [comment]
That's not a fix. It's a workaround. This gem is supposed to provide minitest::spec style assertions for Capybara, but it doesn't work in Cucumber. Can we reopen this bug? It applies to me too, and I'm not content with the workaround.

**Comment by toby-1-kenobi** [comment]
I can confirm that `refute_selector(".my_css_class")` works in a cucumber step, but `page.wont_have_selector(".my_css_class")` gives an error complaining that  `refute_selector` is undefined for `nil:NilClass`

**Comment by ordinaryzelig** [comment]
Any chance you could create a repo for me with your environment and a failing test? Would help me a ton to debug.

**Comment by toby-1-kenobi** [comment]
Here's the repo of my current project
https://github.com/toby-1-kenobi/sag_reporter
to get the failure:
`cucumber features/user_may_have_multiple_geo_states.feature`

is this ok? or do you want a smaller repo, just enough to reproduce the problem?

**Comment by ordinaryzelig** [comment]
> is this ok? or do you want a smaller repo, just enough to reproduce the problem?

Please, if it's not too much trouble. Would help to isolate the problem.

**Comment by toby-1-kenobi** [comment]
OK, when I get some time to do that.

**Comment by toby-1-kenobi** [comment]
Here's the repo for a bare rails project with just enough code to produce the bug:
https://github.com/toby-1-kenobi/bug-demo

run `cucumber` to produce the bug
run `rake test TEST=test/features/no_bug_here.rb`  to have the same test run outside cucumber and see that no bug is there.

**Comment by ordinaryzelig** [comment]
@toby-1-kenobi I was able to get it to work, and I added, but it's not a good solution. Not sure how long it will last as a "feature". I'm open to suggestions. See https://github.com/toby-1-kenobi/bug-demo/pull/1.

**Comment by ordinaryzelig** [comment]
There are also failing tests. Will look into those when I can. But do let me know if you think the solution is good/bad.

**Comment by toby-1-kenobi** [comment]
Why do you think the solution is not good?

**Comment by toby-1-kenobi** [comment]
It looks like the the key is having the code

    Before do
      Thread.current[:current_spec] = self
    end

which I put into `features/support/env.rb` and it works. (See commit "Workaround" in the bug-demo repo). Thanks @ordinaryzelig.

putting this code into `rnv.rb` is a workaround with which I am satisfied, and I prefer it to cloning `capybara_minitest_spec` and putting the code in there.

**Comment by ordinaryzelig** [comment]
I don't particularly like it because it's not intuitive. It's really just a bandaid. I just figured out what was missing from Minitest::Spec's initializer and copied it in the `Before` statement. A better solution would be to somehow make `Cucumber::Rails::World` a subclass of `Minitest::Spec`. Then it would properly get everything it's supposed to get. It would work with future versions.

Since you find the solution good enough, I'll add it to the README, but I don't feel like it's good enough to support in the gem itself, even unofficially.

**Comment by f3ndot** [comment]
@ordinaryzelig we apply a workaround by doing the following in `env.rb`:

```ruby
require 'minitest/spec'

# ...

# Make minitest assertions available in Cucumber
class MinitestWorld
  extend Minitest::Assertions
  attr_accessor :assertions

  def initialize
    self.assertions = 0
  end
end

World do
  MinitestWorld.new
end
```

Is this more palatable?

**Comment by ordinaryzelig** [comment]
@f3ndot I gave it a shot (still not familiar with cucumber at all). I copied your code into the bug demo above in `env.rb` and got:

```
You can only pass a proc to #World once, but it's happening
in 2 places:

cucumber-rails-1.4.2/lib/cucumber/rails/world.rb:24:in `World'
features/support/env.rb:73:in `World'

Use Ruby modules instead to extend your worlds. See the Cucumber::RbSupport::RbDsl#World RDoc
or http://wiki.github.com/cucumber/cucumber/a-whole-new-world.

 (Cucumber::RbSupport::MultipleWorld)
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:87:in `build_rb_world_factory'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_dsl.rb:15:in `build_rb_world_factory'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_dsl.rb:50:in `World'
/Users/ningja/dev/projects/bug-demo/features/support/env.rb:73:in `<top (required)>'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:42:in `run!'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/ningja/.gem/ruby/2.3.0/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
/Users/ningja/.gem/ruby/2.3.0/bin/cucumber:23:in `load'
/Users/ningja/.gem/ruby/2.3.0/bin/cucumber:23:in `<main>'
```

I'm assuming you're using plain cucumber, and not cucumber-rails?

Either way, I think my main goal is to have the world class somehow run everything that happens in [Minitest::Spec's constructor](https://github.com/seattlerb/minitest/blob/baf6010053279f75f561f6a599d8837151327588/lib/minitest/spec.rb#L103). Currently, the only thing it needs is the Thread snippet, which I've already added to [`capybara_minitest_spec/cucumber_rails.rb`](https://github.com/ordinaryzelig/capybara_minitest_spec/blob/3a8b4bf9500efc2c6488b5d75e4dd3e22bb12640/lib/capybara_minitest_spec/cucumber_rails.rb) but don't particularly like as a solution (also why I haven't released it). And the workaround is so easy that I figure it's not worth adding to this gem.

**Comment by f3ndot** [comment]
Yes, we're using plain cucumber. And fair enough. Hopefully it help Google-searchers in the future 😄

**Comment by ordinaryzelig** [comment]
Also, there's a note in the readme pointing here. :smile:
