### ISSUE TITLE
NoMethodError: undefined method `assert_page_has_content' for nil:NilClass

### ISSUE THREAD

**Issue by chengguangnan** [ordinaryzelig/capybara_minitest_spec#12]
I upgraded an old rails project to rails 4.1.0 with "bundle update" and it seems that something in this gem got broke. 

I was using code like:
```
page.must_have_content('Title')
```
But now it says 
```
NoMethodError: undefined method `assert_page_has_content' for nil:NilClass
```

I changed my code to `assert has_text?('New Project')` which works. 

JFYI.

**Comment by dsandber** [comment]
I'm having the same issue.  ("NoMethodError: undefined method `assert_page_has_content' for nil:NilClass")  doing page.methods.sort.grep(/must_/) yields:

`
=> [:must_be,
 :must_be_close_to,
 :must_be_empty,
 :must_be_instance_of,
 :must_be_kind_of,
 :must_be_nil,
 :must_be_same_as,
 :must_be_silent,
 :must_be_within_delta,
 :must_be_within_epsilon,
 :must_become_closed,
 :must_equal,
 :must_have_button,
 :must_have_checked_field,
 :must_have_content,
 :must_have_css,
 :must_have_field,
 :must_have_link,
 :must_have_select,
 :must_have_selector,
 :must_have_table,
 :must_have_text,
 :must_have_title,
 :must_have_unchecked_field,
 :must_have_xpath,
 :must_include,
 :must_match,
 :must_output,
 :must_raise,
 :must_respond_to,
 :must_throw]
`

**Comment by ordinaryzelig** [comment]
@dsandber could you give me your backtrace?

**Comment by dsandber** [comment]
It's strange -- it didn't point to where the actual error was, just said:

`
NoMethodError: undefined method `must_have_content' for #<IndexTest:0x007fbf9570e9d0>
    test/integration/index_test.rb:102:in `block in <class:IndexTest>'
`

The problem appeared when I upgraded to Rails 4.1.  Have you tried that?

**Comment by ordinaryzelig** [comment]
I've been using this with Rails 4.1. Never seen this error before.

**Comment by ordinaryzelig** [comment]
I'll keep digging. in the meantime, an easily reproducible test case would be useful.

**Comment by shawnstephens** [comment]
I'm using Rails 4.2.2 and I had to add the following gem for this to work.
```
  gem 'minitest-spec-rails'
```

**Comment by moger777** [comment]
I get this issue on one test if the method is called in a setup block, does not seem to be issue otherwise.

**Comment by ordinaryzelig** [comment]
If you all are using `ActionDispatch::IntegrationTest`, you just need to do:

```ruby
# Maybe in a helper or something?
ActionDispatch::IntegrationTest.extend Minitest::Spec::DSL
```

@f-plante, I used your [example test](https://github.com/ordinaryzelig/capybara_minitest_spec/issues/12#issuecomment-57274865), and this fixed it. Thanks for providing it.
