### ISSUE TITLE
Problem with poltergeist

### ISSUE THREAD

**Issue by Paxa** [ordinaryzelig/capybara_minitest_spec#18]
When I run more then 1 test scenario some response treated as text not as html

Solved by adding:

``` ruby
      after do
        Capybara.reset_sessions!
        Capybara.use_default_driver
      end
```

Inspired by https://github.com/jnicklas/capybara/blob/master/lib/capybara/rspec.rb

**Comment by ordinaryzelig** [comment]
Could you provide a small example that I could reproduce?
